name: create scripts archive

on: 
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: "To distinguish workflow_dispatch from merged and closed PR"
        type: boolean
        required: false
        default: true      
  
jobs:
  create_archive:
    name: create an archive
    runs-on: ubuntu-latest
    outputs:
      archive-url: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    if: (github.event.pull_request.merged == true) || (inputs.manual_trigger == true)
    steps:
      - name: pull down repository
        uses: actions/checkout@v5
        with:
          path: main
      - name: create the script archive file
        run: |
          mkdir out
          git archive --worktree-attributes --format=tar.gz -o "./out/archive.tar.gz" HEAD scripts
      - name: Archive production artifacts
        id: artifact-upload-step 
        uses: actions/upload-artifact@v4
        with:
          name: archive.tar.gz
          overwrite: true
          path: |
            out

  update_readme:
    name: update the readme file with link to latest archive
    runs-on: ubuntu-latest
    needs: create_archive
    env: 
      ARCH_URL: ${{needs.create_archive.outputs.archive-url}}
    steps:
      - name: pull down repository
        uses: actions/checkout@v5
        with:
          token: ${{secrets.GHAKEY}}
      - name: update README.md
        run: |
          sed -i "s|\[Current scripts archive\](.*)|[Current scripts archive](${ARCH_URL})|" scripts/README.md
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit -am "README update"
          git push --no-verify


            
