on: 
  pull_request:
    branches: [main]
    types: [closed]
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: "To distinguish workflow_dispatch from merged and closed PR"
        type: boolean
        required: false
        default: true      
  
jobs:
  create_archive_job:
    name: create an archive
    runs-on: ubuntu-latest
    if: (github.event.pull_request.merged == true) || (inputs.manual_trigger == true)
    steps:
    - uses: actions/checkout@v5
    - run: |
        mkdir out
        git archive --worktree-attributes --format=tar.gz -o "./out/archive.tar.gz" HEAD scripts
  
